### ISSUE TITLE
TFT reset bug

### ISSUE THREAD

**Issue by hydra** [martnak/STM32-ILI9341#1]
Hi, no time for a PR right now but just letting you know the TFT reset has a bug.

https://github.com/martnak/STM32-ILI9341/blob/master/Src/ILI9341/ILI9341_STM32_Driver.c#L145-L149

The reset line should be RESET (LOW) then SET (high).  Looks like a copy/paste error in the code.

**Comment by martnak** [comment]
Thanks for pointing it out and letting me know! I've just updated it.

**Comment by martnak** [comment]
https://github.com/martnak/STM32-ILI9341/commit/2ed24b6fbbd080bb79a21d21ba395926898ce31a
