### ISSUE TITLE
how to generate snow_tiger.h

### ISSUE THREAD

**Issue by lutfisan** [martnak/STM32-ILI9341#3]
how to generate snow_tiger.h?

**Comment by martnak** [comment]
https://github.com/martnak/STM32-ILI9341/blob/2ed24b6fbbd080bb79a21d21ba395926898ce31a/Src/ILI9341/ILI9341_GFX.c#L271

http://www.digole.com/tools/PicturetoC_Hex_converter.php
65K colour (2Bytes / Pixel)
